sudo: required
dist: trusty
language: node_js
node_js:
  - "8.4"
script:
  - npm run build
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - cmake
      - libblas-dev
      - libopenblas-dev
      - hdf5
